spring:
  config:
    import: optional:file:.env[.properties]
  ai:
    openai:
      api-key: ${DEEPSEEK_API_KEY}
      base-url: https://api.deepseek.com/
      chat:
        options:
          model: deepseek-v4-flash
        response-format:
          type: JSON_OBJECT
  application:
    name: Mid-term
  datasource:
    url: ${DB_URL:jdbc:mysql://127.0.0.1:3308/ai_decision?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:1234}
      database: 0
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2

jwt:
  secret: ${JWT_SECRET}
  expiration: 7200

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: qg.po.midterm.entity

  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

tavily:
  api-key: ${TAVILY_API_KEY:}

# Sentry 错误日志监控配置
sentry:
  # 必须配置 DSN，否则 Sentry 不会启动。这个链接是从你刚才贴出的官方文档中提取的
  dsn: https://e46378eb75244b37876c1adcfe6990fd@o4511829869199360.ingest.us.sentry.io/4511830110306304
  send-default-pii: true
  # 区分环境
  environment: ${SPRING_PROFILES_ACTIVE:development}
  # 发送 100% 的错误（生产环境可以调低）
  traces-sample-rate: 1.0
  # 开启日志收集，使得 log.error 也会被作为错误上报，并且带上前面的正常日志作为面包屑
  logging:
    minimum-event-level: error
    minimum-breadcrumb-level: info
  logs:
    enabled: true
